steps:
  - name: 'gcr.io/cloud-builders/npm'
    id: 'Install dependencies'
    entrypoint: 'npm'
    args: ['install']

  - name: 'gcr.io/cloud-builders/npm'
    id: 'Build React App'
    entrypoint: 'npm'
    args: ['run', 'build']

  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'Upload to Cloud Storage'
    args: ['-m', 'cp', '-r', 'build/*', 'gs://YOUR_BUCKET_NAME']

images: []
